import { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, Copy, Check, Download } from 'lucide-react';

const RobotsTxtGenerator = () => {
    const [userAgent, setUserAgent] = useState('*');
    const [disallowPaths, setDisallowPaths] = useState('/admin/\n/private/');
    const [allowPaths, setAllowPaths] = useState('');
    const [sitemap, setSitemap] = useState('');
    const [crawlDelay, setCrawlDelay] = useState('');
    const [copied, setCopied] = useState(false);

    const userAgents = [
        { id: '*', name: 'All Bots' },
        { id: 'Googlebot', name: 'Google' },
        { id: 'Bingbot', name: 'Bing' },
        { id: 'Slurp', name: 'Yahoo' },
        { id: 'DuckDuckBot', name: 'DuckDuckGo' },
        { id: 'Baiduspider', name: 'Baidu' }
    ];

    const presets = [
        {
            name: 'Allow All',
            config: { userAgent: '*', disallow: '', allow: '/', sitemap: '', crawlDelay: '' }
        },
        {
            name: 'Block All',
            config: { userAgent: '*', disallow: '/', allow: '', sitemap: '', crawlDelay: '' }
        },
        {
            name: 'Standard Website',
            config: { userAgent: '*', disallow: '/admin/\n/private/\n/api/', allow: '', sitemap: 'https://example.com/sitemap.xml', crawlDelay: '' }
        },
        {
            name: 'E-commerce',
            config: { userAgent: '*', disallow: '/cart/\n/checkout/\n/account/\n/admin/', allow: '', sitemap: 'https://example.com/sitemap.xml', crawlDelay: '' }
        }
    ];

    const generateRobotsTxt = () => {
        let content = `# robots.txt generated by KaamBox\n\n`;

        content += `User-agent: ${userAgent}\n`;

        if (disallowPaths.trim()) {
            disallowPaths.split('\n').forEach(path => {
                if (path.trim()) {
                    content += `Disallow: ${path.trim()}\n`;
                }
            });
        }

        if (allowPaths.trim()) {
            allowPaths.split('\n').forEach(path => {
                if (path.trim()) {
                    content += `Allow: ${path.trim()}\n`;
                }
            });
        }

        if (crawlDelay) {
            content += `Crawl-delay: ${crawlDelay}\n`;
        }

        if (sitemap.trim()) {
            content += `\n# Sitemap\n`;
            sitemap.split('\n').forEach(url => {
                if (url.trim()) {
                    content += `Sitemap: ${url.trim()}\n`;
                }
            });
        }

        return content;
    };

    const applyPreset = (preset) => {
        setUserAgent(preset.config.userAgent);
        setDisallowPaths(preset.config.disallow);
        setAllowPaths(preset.config.allow);
        setSitemap(preset.config.sitemap);
        setCrawlDelay(preset.config.crawlDelay);
    };

    const copyToClipboard = () => {
        navigator.clipboard.writeText(generateRobotsTxt());
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    const downloadFile = () => {
        const blob = new Blob([generateRobotsTxt()], { type: 'text/plain' });
        const link = document.createElement('a');
        link.href = URL.createObjectURL(blob);
        link.download = 'robots.txt';
        link.click();
    };

    return (
        <div className="space-y-6">
            <div className="text-center mb-6">
                <h2 className="text-lg font-semibold mb-2">robots.txt Generator</h2>
                <p className="text-[var(--text-muted)] text-sm">Create robots.txt for search engine crawlers</p>
            </div>

            <div className="space-y-4">
                {/* Presets */}
                <div>
                    <label className="block text-sm font-medium mb-2">Quick Presets</label>
                    <div className="flex flex-wrap gap-2">
                        {presets.map(p => (
                            <button
                                key={p.name}
                                onClick={() => applyPreset(p)}
                                className="px-3 py-1.5 text-sm bg-[var(--bg-tertiary)] rounded-lg hover:bg-[var(--bg-secondary)] transition-colors"
                            >
                                {p.name}
                            </button>
                        ))}
                    </div>
                </div>

                <div>
                    <label className="block text-sm font-medium mb-2">User-agent</label>
                    <div className="flex flex-wrap gap-2">
                        {userAgents.map(ua => (
                            <button
                                key={ua.id}
                                onClick={() => setUserAgent(ua.id)}
                                className={`px-3 py-1.5 rounded-lg text-sm transition-colors ${userAgent === ua.id ? 'bg-[var(--accent-primary)] text-white' : 'bg-[var(--bg-tertiary)]'
                                    }`}
                            >
                                {ua.name}
                            </button>
                        ))}
                    </div>
                </div>

                <div>
                    <label className="block text-sm font-medium mb-2">Disallow Paths (one per line)</label>
                    <textarea
                        value={disallowPaths}
                        onChange={(e) => setDisallowPaths(e.target.value)}
                        placeholder="/admin/&#10;/private/"
                        className="input w-full h-24 resize-none font-mono text-sm"
                    />
                </div>

                <div>
                    <label className="block text-sm font-medium mb-2">Allow Paths (one per line)</label>
                    <textarea
                        value={allowPaths}
                        onChange={(e) => setAllowPaths(e.target.value)}
                        placeholder="/public/"
                        className="input w-full h-16 resize-none font-mono text-sm"
                    />
                </div>

                <div>
                    <label className="block text-sm font-medium mb-2">Sitemap URL(s)</label>
                    <input
                        type="text"
                        value={sitemap}
                        onChange={(e) => setSitemap(e.target.value)}
                        placeholder="https://example.com/sitemap.xml"
                        className="input w-full font-mono text-sm"
                    />
                </div>

                <div>
                    <label className="block text-sm font-medium mb-2">Crawl Delay (seconds)</label>
                    <input
                        type="number"
                        value={crawlDelay}
                        onChange={(e) => setCrawlDelay(e.target.value)}
                        placeholder="Optional"
                        className="input w-full"
                    />
                </div>

                {/* Preview */}
                <div className="p-4 bg-[var(--bg-tertiary)] rounded-xl">
                    <p className="text-xs text-[var(--text-muted)] mb-2">Preview:</p>
                    <pre className="text-sm font-mono text-green-400 whitespace-pre-wrap overflow-x-auto">
                        {generateRobotsTxt()}
                    </pre>
                </div>

                <div className="flex gap-2">
                    <motion.button
                        whileHover={{ scale: 1.02 }}
                        whileTap={{ scale: 0.98 }}
                        onClick={copyToClipboard}
                        className="btn-primary flex-1"
                    >
                        {copied ? <Check className="w-4 h-4 mr-2" /> : <Copy className="w-4 h-4 mr-2" />}
                        {copied ? 'Copied!' : 'Copy'}
                    </motion.button>
                    <motion.button
                        whileHover={{ scale: 1.05 }}
                        whileTap={{ scale: 0.95 }}
                        onClick={downloadFile}
                        className="p-3 rounded-xl bg-[var(--bg-tertiary)]"
                    >
                        <Download className="w-5 h-5" />
                    </motion.button>
                </div>
            </div>
        </div>
    );
};

export default RobotsTxtGenerator;
